version: '3.9'
services:
  backend:
    build: .
    container_name: warmshower_backend
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    container_name: warmshower_redis
    command: ["redis-server", "--appendonly", "no"]  # ephemeral (no persistence)
    ports:
      - "6379:6379"
